In [1]:
import torch

In [2]:
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
print(b.shape[0])

4


In [6]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [7]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())
print(d.std())

tensor(1.5050)
tensor(1.5050, dtype=torch.float64)


In [13]:
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
b = b.view(1,-1)
print(b)
print(b.shape)
print('\n')
three_dim = torch.randn(2,3,4)
print(three_dim.view(2,12))
print(three_dim.view(2,-1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])


tensor([[-0.5643,  0.4349,  0.5832, -1.1766, -0.9057, -0.2432,  0.3097, -1.4546,
         -0.2950, -0.2917, -1.1964, -0.8733],
        [-0.7681, -1.6774, -1.1780,  1.8996,  0.9538, -1.6882, -1.1463,  1.5352,
         -0.1275,  1.9035, -1.5479,  0.9656]])
tensor([[-0.5643,  0.4349,  0.5832, -1.1766, -0.9057, -0.2432,  0.3097, -1.4546,
         -0.2950, -0.2917, -1.1964, -0.8733],
        [-0.7681, -1.6774, -1.1780,  1.8996,  0.9538, -1.6882, -1.1463,  1.5352,
         -0.1275,  1.9035, -1.5479,  0.9656]])


In [14]:
r = torch.rand(4,4)
print(r)

tensor([[0.0578, 0.6740, 0.1284, 0.2071],
        [0.9002, 0.3805, 0.0907, 0.7371],
        [0.2113, 0.7672, 0.6542, 0.5547],
        [0.4361, 0.9022, 0.1914, 0.2274]])


In [15]:
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 2.4393, -0.7274,  1.2998,  1.3135],
        [ 0.5891,  1.0965, -1.3559, -0.7842],
        [ 1.0427, -0.3909,  0.3661,  0.2400],
        [ 0.6558, -0.0834,  0.8879,  0.6317]])
torch.float32


In [16]:
in_array = torch.randint(6,10, (5,))
print(in_array)
print(in_array.dtype)

tensor([8, 8, 6, 9, 6])
torch.int64


In [17]:
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[9, 8, 9],
        [7, 9, 8],
        [8, 9, 8]])


In [18]:
print(torch.numel(in_array))
print(torch.numel(in_array2))

5
9


In [19]:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
o = torch.ones(3, 3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [20]:
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)

tensor([[ 0.1431, -0.4595, -0.1280,  1.7773],
        [ 1.5285,  0.4832,  0.1696,  1.7182],
        [ 1.0328, -0.9389,  0.9240,  0.5985],
        [ 1.6948, -1.0277, -0.4202, -2.3371]], dtype=torch.float64)


In [21]:
add_result = torch.add(r,r2)
print(add_result)

tensor([[ 2.4971, -0.0534,  1.4283,  1.5206],
        [ 1.4893,  1.4770, -1.2652, -0.0471],
        [ 1.2540,  0.3763,  1.0203,  0.7946],
        [ 1.0919,  0.8188,  1.0793,  0.8592]])


In [22]:
r2.add_(r)
print(r2)

tensor([[ 2.4971, -0.0534,  1.4283,  1.5206],
        [ 1.4893,  1.4770, -1.2652, -0.0471],
        [ 1.2540,  0.3763,  1.0203,  0.7946],
        [ 1.0919,  0.8188,  1.0793,  0.8592]])


In [23]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([-0.0534,  1.4770,  0.3763,  0.8188])
tensor([[ 2.4971, -0.0534],
        [ 1.4893,  1.4770],
        [ 1.2540,  0.3763],
        [ 1.0919,  0.8188]])
tensor([[ 2.4971, -0.0534,  1.4283,  1.5206],
        [ 1.4893,  1.4770, -1.2652, -0.0471],
        [ 1.2540,  0.3763,  1.0203,  0.7946]])
tensor(0.7946)
0.7946198582649231
tensor([1.2540, 0.3763, 1.0203, 0.7946])
