In [1]:
#numpy bridge
import torch
import numpy as np

In [2]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [3]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [4]:
r2 = torch.randn(4,4)
#throw the tensor to GPU to compute
r2 = r2.cuda()
print(r2)

tensor([[ 1.0913,  0.6553, -0.1315,  0.3045],
        [ 2.0415, -0.6233, -0.1290,  1.8594],
        [-1.0400,  2.2507,  2.1910,  0.0384],
        [-0.6325,  0.6967, -0.1766, -0.5784]], device='cuda:0')


In [5]:
add_result = torch.randn(4,4)
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

True
tensor([[-1.1523, -1.1719,  1.2046, -1.2600],
        [-1.0269,  1.1906, -0.5445, -1.3652],
        [-0.4619,  0.5583,  0.2839,  0.1858],
        [-0.4606, -1.6566, -0.8617,  0.1745]], device='cuda:0')


In [6]:
add_result.add_(r2)
print(add_result)

tensor([[-0.0610, -0.5166,  1.0731, -0.9555],
        [ 1.0146,  0.5673, -0.6734,  0.4942],
        [-1.5018,  2.8090,  2.4749,  0.2242],
        [-1.0931, -0.9599, -1.0383, -0.4038]], device='cuda:0')


In [7]:
a = [2, 3, 4, 1]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

[2, 3, 4, 1]
tensor([2, 3, 4, 1]) torch.int64


In [8]:
data = [[1., 2.], [3., 4.], [5., 6.], [7., 8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


In [9]:
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
con_1 = torch.cat([first_1, second_1])
print('\n')
print(con_1)
print('\n')
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
con_2 = torch.cat([first_2, second_2], 1)
print('\n')
print(con_2)
print('\n')

tensor([[-0.1893,  0.6330,  0.5923,  0.6016,  0.4422],
        [ 0.1990, -1.2316, -0.4411, -1.3718, -0.7151]])
tensor([[ 1.1220,  1.3905,  1.8308, -0.4374,  0.8936],
        [-2.6235, -0.3487,  0.5836, -0.9131,  1.6384],
        [-0.0761,  0.9476,  0.1630,  0.6183,  0.2169]])


tensor([[-0.1893,  0.6330,  0.5923,  0.6016,  0.4422],
        [ 0.1990, -1.2316, -0.4411, -1.3718, -0.7151],
        [ 1.1220,  1.3905,  1.8308, -0.4374,  0.8936],
        [-2.6235, -0.3487,  0.5836, -0.9131,  1.6384],
        [-0.0761,  0.9476,  0.1630,  0.6183,  0.2169]])


tensor([[-0.8141, -1.5896, -0.5722],
        [-0.9011, -0.1166,  1.6795]])
tensor([[-0.8392, -2.2798,  0.2022, -1.0959,  1.4091],
        [-0.1422,  0.0318,  0.1775,  0.9107,  1.8256]])


tensor([[-0.8141, -1.5896, -0.5722, -0.8392, -2.2798,  0.2022, -1.0959,  1.4091],
        [-0.9011, -0.1166,  1.6795, -0.1422,  0.0318,  0.1775,  0.9107,  1.8256]])




In [10]:
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1, 1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c, 2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.6248, 0.8942, 0.6626, 0.1979],
         [0.1428, 0.5534, 0.4331, 0.0940],
         [0.1309, 0.0348, 0.5476, 0.2549]],

        [[0.4734, 0.3673, 0.9955, 0.2063],
         [0.0194, 0.7572, 0.6692, 0.1322],
         [0.3205, 0.9291, 0.7288, 0.0814]]])


tensor([[0.6626, 0.4331, 0.5476],
        [0.9955, 0.6692, 0.7288]])
torch.Size([2, 3])


tensor([[[0.6626],
         [0.4331],
         [0.5476]],

        [[0.9955],
         [0.6692],
         [0.7288]]])
torch.Size([2, 3, 1])
